<?php session_start();$user_email=$_SESSION['user_email']??'rpms@ceu.edu.ph';?>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Notifications | PRISM Admin</title><script>try{if(localStorage.getItem('prismTheme')==='dark')document.documentElement.classList.add('dark-theme')}catch(_){}</script><link rel="icon" href="assets/images/prismicon.png"><link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="assets/css/dashboard.css"><link rel="stylesheet" href="assets/css/admin-management.css"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css"><link rel="stylesheet" href="assets/css/dashboard-sidebar.css"><link rel="stylesheet" href="assets/css/admin-notifications.css"></head><body data-admin-user="<?php echo htmlspecialchars(hash('sha256',$user_email),ENT_QUOTES); ?>"><div class="container"><?php require __DIR__ . '/admin_navigation.php'; ?><main class="main-content management-page"><header class="topbar"><div><h1>Notification Center</h1></div><div class="theme-toggle" id="themeToggle"><i class="fa-solid fa-sun light-icon"></i><i class="fa-solid fa-moon dark-icon"></i></div></header><div class="notification-layout">
<section class="management-card notification-composer"><div class="notification-card-heading"><h2>Send Notification</h2></div>
<form id="notificationForm"><div class="notification-fields"><label for="noticeAudience">Recipients<select id="noticeAudience"><option>All Students</option><option>All Faculty</option><option>Students and Faculty</option><option>Specific Research Group</option></select><small id="recipientCount"></small></label><label for="noticeType">Notification Type<select id="noticeType"><option>Status Update</option><option>Reminder</option><option>Follow-up</option><option>Submission Confirmation</option></select></label></div>
<label id="groupLabel" for="noticeGroup" hidden>Research group<input id="noticeGroup" maxlength="80" placeholder="Enter the research group"></label>
<label for="noticeMessage">Message<textarea id="noticeMessage" rows="8" maxlength="600" required placeholder="Type your notification message here..."></textarea></label><div class="notification-message-meta"><span id="messageCount">0 / 600</span></div>
<div class="notification-reminder"><label class="notification-check" for="automatedNotice"><input id="automatedNotice" type="checkbox"><span>Automated Reminder</span></label><label id="scheduleLabel" for="noticeSchedule" hidden>Send date<input id="noticeSchedule" type="datetime-local"></label></div>
<p id="notificationStatus" role="status"></p><div class="notification-controls"><button type="button" id="cancelNotification" class="notification-secondary">Cancel</button><button class="management-primary" type="submit"><i class="fa-solid fa-paper-plane" aria-hidden="true"></i> Send Notification</button></div></form></section>
<section class="management-card notification-history"><div class="notification-card-heading"><h2>Notification History</h2><p id="noticeCount" hidden></p></div><div class="notification-table-wrap"><table><thead><tr><th>Date</th><th>Recipient</th><th>Type</th><th>Message Preview</th><th>Delivery Status</th><th>Action</th></tr></thead><tbody id="noticeHistory"></tbody></table></div></section></div>
<dialog id="notificationConfirm" class="notification-dialog" aria-labelledby="notificationConfirmTitle"><h2 id="notificationConfirmTitle">Send Notification?</h2><p id="notificationConfirmMessage"></p><div class="notification-controls"><button type="button" id="cancelConfirm" class="notification-secondary">Cancel</button><button type="button" id="confirmSend" class="management-primary">Confirm Send</button></div></dialog>
<dialog id="notificationDetail" class="notification-dialog" aria-labelledby="notificationDetailTitle"><h2 id="notificationDetailTitle">Notification Details</h2><p id="notificationDetailMeta"></p><p id="notificationDetailMessage"></p><form method="dialog" class="notification-controls"><button class="notification-secondary">Close</button></form></dialog>
</main></div><script src="assets/js/admin-notifications.js"></script><script src="assets/js/dashboard-sidebar.js"></script></body></html>
