<?php
session_start();
$managementType = ($managementType ?? '') === 'faculty' ? 'faculty' : 'student';
$isFaculty = $managementType === 'faculty';
$user_name = $_SESSION['user_name'] ?? 'CEU RPMS'; $user_email = $_SESSION['user_email'] ?? 'rpms@ceu.edu.ph';
$user_role = $_SESSION['user_role'] ?? 'RPMS Administrator'; $profile_img = 'assets/images/default-avatar.svg';
?>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?php echo $isFaculty?'Research Adviser':'Student'; ?> Management | PRISM</title><script>try{if(localStorage.getItem('prismTheme')==='dark')document.documentElement.classList.add('dark-theme')}catch(_){}</script><link rel="icon" href="assets/images/prismicon.png"><link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="assets/css/dashboard.css"><link rel="stylesheet" href="assets/css/admin-management.css"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css"><link rel="stylesheet" href="assets/css/dashboard-sidebar.css"></head>
<body data-admin-user="<?php echo htmlspecialchars(hash('sha256',$user_email),ENT_QUOTES); ?>" data-management="<?php echo $managementType; ?>"><div class="container"><?php require __DIR__ . '/admin_navigation.php'; ?>
<main class="main-content management-page"><header class="topbar"><div><h1><?php echo $isFaculty?'Research Adviser':'Student'; ?> Management</h1><p><?php echo $isFaculty?'Manage research adviser accounts and research-group assignments.':'Manage records, research groups, and research adviser assignments.'; ?></p></div><div class="theme-toggle" id="themeToggle"><i class="fa-solid fa-sun light-icon"></i><i class="fa-solid fa-moon dark-icon"></i></div></header><section class="management-controls"><div class="management-search"><i class="fa-solid fa-magnifying-glass"></i><input id="recordSearch" placeholder="Search records"></div><button class="management-primary" id="addRecord"><i class="fa-solid fa-plus"></i> Add <?php echo $isFaculty?'Research Adviser':'Student'; ?></button></section><section class="management-card"><div class="management-card-head"><div><h2><?php echo $isFaculty?'Research Adviser Accounts':'Student Records'; ?></h2><p id="recordCount">0 records</p></div></div><div class="management-table-wrap"><table><thead><tr><?php if($isFaculty): ?><th>Research Adviser</th><th>Employee ID</th><th>Department</th><th>Assigned Groups</th><th>Account</th><?php else: ?><th>Student</th><th>Student ID</th><th>Research / Group</th><th>Assigned Research Adviser</th><th>IERB Status</th><?php endif; ?><th>Actions</th></tr></thead><tbody id="recordRows"></tbody></table></div></section></main></div>
<div class="management-modal" id="recordModal"><div class="management-dialog"><div class="management-modal-head"><div><span>Account record</span><h2 id="modalTitle">Add Record</h2></div><button type="button" id="closeRecord"><i class="fa-solid fa-xmark"></i></button></div><form id="recordForm"><input type="hidden" id="recordId"><div class="management-form-grid"><label>Full name<input id="recordName" required maxlength="120"></label><label><?php echo $isFaculty?'Employee':'Student'; ?> ID<input id="accountId" required maxlength="40"></label><label>Email<input id="recordEmail" type="email" required maxlength="150"></label><?php if($isFaculty): ?><label>Department<input id="department" required maxlength="100"></label><label class="wide">Assigned research groups<input id="groups" maxlength="250" placeholder="GRP-001, GRP-002"></label><label>Account status<select id="accountStatus"><option>Active</option><option>Inactive</option><option>Pending Activation</option></select></label><?php else: ?><label class="wide">Research title<input id="research" maxlength="250"></label><label>Research group<input id="group" maxlength="80"></label><label>Assigned research adviser<select id="faculty"><option value="">Unassigned</option></select></label><label>IERB stage<select id="stage"><option>Stage 1</option><option>Stage 2</option><option>Stage 3</option><option>Stage 4</option><option>Stage 5</option><option>Completed</option></select></label><label>Status<select id="recordStatus"><option>On Track</option><option>Pending</option><option>Delayed</option></select></label><?php endif; ?></div><div class="management-actions"><button type="button" id="cancelRecord">Cancel</button><button class="management-primary" type="submit"><i class="fa-solid fa-floppy-disk"></i> Save record</button></div></form></div></div><script src="assets/js/admin-management.js"></script><script src="assets/js/dashboard-sidebar.js"></script></body></html>
