<?php
session_start();
$user_name = $_SESSION['user_name'] ?? 'CEU RPMS';
$user_email = $_SESSION['user_email'] ?? 'rpms@ceu.edu.ph';
$user_role = $_SESSION['user_role'] ?? 'RPMS Administrator';
$profile_img = 'assets/images/default-avatar.svg';
?>
<!DOCTYPE html><html lang="en"><head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0">
<title>Documents | CEU RPMS Workload Assistant</title>
<script>try{if(localStorage.getItem('prismTheme')==='dark')document.documentElement.classList.add('dark-theme')}catch(_){}</script>
<link rel="icon" type="image/png" href="assets/images/prismicon.png">
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700&display=swap" rel="stylesheet">
<link rel="stylesheet" href="assets/css/dashboard.css"><link rel="stylesheet" href="assets/css/documents.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css">
</head><body data-document-user="<?php echo htmlspecialchars(hash('sha256',$user_email),ENT_QUOTES,'UTF-8'); ?>">
<div class="container"><aside class="sidebar">
<div class="sidebar-header"><img src="assets/images/prismlogo1.png?v=2" alt="PRISM Assistant logo" class="sidebar-brand-logo"><div class="sidebar-brand-copy"><strong>IERB Progress &amp; Reporting System</strong><span>Centro Escolar University - Malolos &bull; RPMS</span></div></div>
<ul class="nav-links"><li><a href="dashboard.php"><i class="fa-solid fa-chart-line"></i><span>Dashboard</span></a></li><li><a href="student.php"><i class="fa-solid fa-user-graduate"></i><span>Students</span></a></li><li><a href="ierbprog.php"><i class="fa-solid fa-file-signature"></i><span>IERB Progress</span></a></li><li class="active"><a href="documents.php"><i class="fa-solid fa-folder-open"></i><span>Documents</span></a></li><li><a href="reports.php"><i class="fa-solid fa-file-pdf"></i><span>Reports</span></a></li><li><a href="calendar.php"><i class="fa-solid fa-calendar-days"></i><span>Calendar</span></a></li></ul>
<div class="sidebar-bottom"><div class="profile-dropdown-wrapper"><div class="sidebar-profile" id="profileToggle"><img src="<?php echo htmlspecialchars($profile_img,ENT_QUOTES,'UTF-8'); ?>" alt="Profile picture"><div class="profile-info"><h4><?php echo htmlspecialchars($user_name,ENT_QUOTES,'UTF-8'); ?></h4><p><?php echo htmlspecialchars($user_role,ENT_QUOTES,'UTF-8'); ?></p></div><i class="fa-solid fa-chevron-down dropdown-arrow"></i></div><div class="profile-menu" id="profileMenu"><a href="#"><i class="fa-solid fa-user-gear"></i> Profile</a><a href="#"><i class="fa-solid fa-gear"></i> Settings</a><a href="#"><i class="fa-solid fa-sliders"></i> Activity Logs</a><hr><a href="logout.php" class="logout-btn"><i class="fa-solid fa-right-from-bracket"></i> Log Out</a></div></div></div>
</aside><main class="main-content documents-page">
<header class="topbar"><div class="documents-heading"><h1>Documents</h1><p>Centralized storage for research and IERB files.</p></div><div class="top-controls"><div class="theme-toggle" id="themeToggle" title="Toggle light or dark theme"><i class="fa-solid fa-sun light-icon"></i><i class="fa-solid fa-moon dark-icon"></i></div></div></header>
<section class="document-controls"><div class="document-search"><i class="fa-solid fa-magnifying-glass"></i><input id="documentSearch" type="search" placeholder="Search file name, student, or document type"></div><div class="document-actions"><select id="documentTypeFilter"><option value="">All document types</option></select><div class="view-switch" aria-label="Document view"><button class="active" id="tableViewButton" title="Table view"><i class="fa-solid fa-table-list"></i></button><button id="folderViewButton" title="Folder view"><i class="fa-solid fa-folder-tree"></i></button></div><button class="upload-document-button" id="uploadDocumentButton"><i class="fa-solid fa-upload"></i> Upload Document</button></div></section>
<section class="documents-content"><div class="documents-section-heading"><div><h2>Document Repository</h2><p id="documentCount">0 documents</p></div></div>
<div class="documents-table-wrap" id="documentsTableView"><table class="documents-table"><thead><tr><th>File Name</th><th>Uploaded By</th><th>Date Uploaded</th><th>Student Associated</th><th>Category</th><th>Actions</th></tr></thead><tbody id="documentsTableBody"></tbody></table></div>
<div class="folder-view" id="documentsFolderView"></div></section>
</main></div>

<div class="document-modal" id="uploadModal" aria-hidden="true"><div class="document-modal-dialog"><div class="document-modal-heading"><div><span>Repository upload</span><h2>Upload Document</h2></div><button data-close="uploadModal" aria-label="Close"><i class="fa-solid fa-xmark"></i></button></div><form id="uploadForm" enctype="multipart/form-data"><div class="file-drop"><input id="documentFile" name="document" type="file" accept=".pdf,.doc,.docx,.txt,.rtf,.odt" required><i class="fa-solid fa-cloud-arrow-up"></i><strong>Choose a research document</strong><span>PDF, Word, text, RTF, or ODT up to 20 MB</span></div><div class="document-form-grid"><div><label for="documentStudent">Student name</label><input id="documentStudent" name="student" maxlength="120" required></div><div><label for="documentType">Document type</label><div class="document-type-control"><select id="documentType" name="documentType" required></select><button type="button" id="manageDocumentTypes" title="Manage document types" aria-label="Manage document types"><i class="fa-solid fa-pen"></i></button></div></div><div><label for="documentStage">IERB stage</label><select id="documentStage" name="stage" required><option>Stage 1</option><option>Stage 2</option><option>Stage 3</option><option>Stage 4</option><option>Stage 5</option><option>Completed</option></select></div></div><div class="document-modal-actions"><button type="button" class="doc-secondary" data-close="uploadModal">Cancel</button><button type="submit" class="doc-primary"><i class="fa-solid fa-upload"></i> Upload</button></div></form></div></div>
<div class="document-modal" id="documentTypesModal" aria-hidden="true"><div class="document-modal-dialog type-manager-dialog"><div class="document-modal-heading"><div><span>Repository settings</span><h2>Document Types</h2></div><button data-close="documentTypesModal" aria-label="Close"><i class="fa-solid fa-xmark"></i></button></div><form id="documentTypeForm" class="add-type-form"><label for="newDocumentType">New document type</label><div><input id="newDocumentType" maxlength="60" placeholder="e.g. Data Privacy Form" required><button type="submit" class="doc-primary"><i class="fa-solid fa-plus"></i> Add</button></div></form><ul class="document-type-list" id="documentTypeList"></ul></div></div>
<div class="document-modal" id="summaryModal" aria-hidden="true"><div class="document-modal-dialog"><div class="document-modal-heading"><div><span>Document analysis</span><h2 id="summaryTitle">AI Summary</h2></div><button data-close="summaryModal" aria-label="Close"><i class="fa-solid fa-xmark"></i></button></div><div class="summary-result" id="summaryResult"></div></div></div>
<script src="assets/js/documents.js"></script></body></html>
