<?php
session_start();date_default_timezone_set('Asia/Manila');header('Content-Type: application/json; charset=UTF-8');
$email=$_SESSION['user_email']??'rpms@ceu.edu.ph';$key=hash('sha256',$email);$base=__DIR__.DIRECTORY_SEPARATOR.'storage'.DIRECTORY_SEPARATOR.'reports'.DIRECTORY_SEPARATOR.$key;if(!is_dir($base)&&!mkdir($base,0775,true)){http_response_code(500);echo json_encode(['ok'=>false,'message'=>'Report storage could not be created.']);exit;}$indexFile=$base.DIRECTORY_SEPARATOR.'index.json';
function reportIndex($f){$d=is_file($f)?json_decode(file_get_contents($f),true):[];return is_array($d)?$d:[];}function saveReportIndex($f,$d){return file_put_contents($f,json_encode(array_values($d),JSON_PRETTY_PRINT),LOCK_EX)!==false;}function payload(){return json_decode(file_get_contents('php://input'),true)?:[];}function pdfEscape($s){$s=preg_replace('/[^\x20-\x7E]/',' ',(string)$s);return str_replace(['\\','(',')'],['\\\\','\(','\)'],$s);}function wrapLines($text,$width=88){$out=[];foreach(preg_split('/\R/',(string)$text) as $line){$wrapped=wordwrap(trim($line),$width,"\n",true);foreach(explode("\n",$wrapped) as $part)$out[]=$part;}return $out;}
function makePdf($title,$lines){$all=array_merge([$title,'CEU RPMS - IERB Progress and Reporting System','Generated: '.date('F j, Y g:i A'),''], $lines);$pages=array_chunk($all,43);$objects=[];$objects[1]='<< /Type /Catalog /Pages 2 0 R >>';$fontId=3;$objects[$fontId]='<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>';$kids=[];$id=4;foreach($pages as $pageLines){$pageId=$id++;$contentId=$id++;$kids[]="$pageId 0 R";$stream="BT\n/F1 10 Tf\n";$y=760;foreach($pageLines as $i=>$line){$font=$i===0?'14':'10';$stream.="/F1 $font Tf 1 0 0 1 50 $y Tm (".pdfEscape($line).") Tj\n";$y-=16;}$stream.="ET";$objects[$pageId]="<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 $fontId 0 R >> >> /Contents $contentId 0 R >>";$objects[$contentId]="<< /Length ".strlen($stream)." >>\nstream\n$stream\nendstream";}$objects[2]='<< /Type /Pages /Kids ['.implode(' ',$kids).'] /Count '.count($kids).' >>';ksort($objects);$pdf="%PDF-1.4\n";$offsets=[0];foreach($objects as $num=>$obj){$offsets[$num]=strlen($pdf);$pdf.="$num 0 obj\n$obj\nendobj\n";}$xref=strlen($pdf);$max=max(array_keys($objects));$pdf.="xref\n0 ".($max+1)."\n0000000000 65535 f \n";for($n=1;$n<=$max;$n++)$pdf.=sprintf('%010d 00000 n ', $offsets[$n]??0)."\n";$pdf.="trailer\n<< /Size ".($max+1)." /Root 1 0 R >>\nstartxref\n$xref\n%%EOF";return $pdf;}
$action=$_GET['action']??'list';$reports=reportIndex($indexFile);
if($action==='list'){echo json_encode(['ok'=>true,'reports'=>$reports]);exit;}
$data=payload();$id=$_GET['id']??$data['id']??'';$found=null;foreach($reports as $r)if(hash_equals((string)$r['id'],(string)$id)){$found=$r;break;}
if($action==='generate'){$type=trim((string)($data['type']??'Progress Report'));$title=trim((string)($data['title']??'IERB Progress Report'));$lines=[];$students=is_array($data['students']??null)?array_slice($data['students'],0,1000):[];
 if($type==='Document Summary'){$lines=array_merge(['DOCUMENT SUMMARY','Document: '.($data['documentName']??'Uploaded document'),''],wrapLines($data['summary']??'No summary available.'));}
 else{$lines[]='REPORT OVERVIEW';$lines[]='Students included: '.count($students);$lines[]='';foreach($students as $s){$lines=array_merge($lines,wrapLines(($s['name']??'Student').' ('.($s['studentId']??'No ID').') - '.($s['stage']??'Stage not set').' - '.($s['status']??'Status not set')));$lines=array_merge($lines,wrapLines('Research: '.($s['researchTitle']??'Not provided')));$lines=array_merge($lines,wrapLines('Pending requirements: '.(($s['requirements']??'')?:'None')));$lines[]='Progress: '.($s['progress']??0).'%';$lines[]='';}}
 $reportId=bin2hex(random_bytes(12));$filename=$reportId.'.pdf';if(file_put_contents($base.DIRECTORY_SEPARATOR.$filename,makePdf($title,$lines),LOCK_EX)===false){http_response_code(500);echo json_encode(['ok'=>false,'message'=>'PDF could not be generated.']);exit;}$entry=['id'=>$reportId,'name'=>$title,'generatedAt'=>date(DATE_ATOM),'type'=>$type,'filename'=>$filename];array_unshift($reports,$entry);if(!saveReportIndex($indexFile,$reports)){@unlink($base.DIRECTORY_SEPARATOR.$filename);http_response_code(500);echo json_encode(['ok'=>false,'message'=>'Report history could not be saved.']);exit;}echo json_encode(['ok'=>true,'report'=>$entry]);exit;}
if(!$found){http_response_code(404);echo json_encode(['ok'=>false,'message'=>'Report not found.']);exit;}$path=$base.DIRECTORY_SEPARATOR.basename($found['filename']);
if($action==='file'){header_remove('Content-Type');header('Content-Type: application/pdf');header('Content-Length: '.filesize($path));header('Content-Disposition: '.(($_GET['download']??'')==='1'?'attachment':'inline').'; filename="'.preg_replace('/[^A-Za-z0-9._-]/','-', $found['name']).'.pdf"');readfile($path);exit;}
if($action==='delete'){if(is_file($path))@unlink($path);$reports=array_values(array_filter($reports,fn($r)=>$r['id']!==$id));saveReportIndex($indexFile,$reports);echo json_encode(['ok'=>true]);exit;}
http_response_code(400);echo json_encode(['ok'=>false,'message'=>'Unknown action.']);
