<?php session_start();$user_name=$_SESSION['user_name']??'CEU RPMS';$user_email=$_SESSION['user_email']??'rpms@ceu.edu.ph';$user_role=$_SESSION['user_role']??'RPMS Administrator';$profile_img='assets/images/default-avatar.svg';?>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>Reports | CEU RPMS Workload Assistant</title><script>try{if(localStorage.getItem('prismTheme')==='dark')document.documentElement.classList.add('dark-theme')}catch(_){}</script><link rel="icon" type="image/png" href="assets/images/prismicon.png"><link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="assets/css/dashboard.css"><link rel="stylesheet" href="assets/css/reports.css"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css"><link rel="stylesheet" href="assets/css/dashboard-sidebar.css"></head>
<body data-report-user="<?php echo htmlspecialchars(hash('sha256',$user_email),ENT_QUOTES,'UTF-8'); ?>"><div class="container"><?php require __DIR__ . '/admin_navigation.php'; ?>
<main class="main-content reports-page"><header class="topbar"><div class="reports-heading"><h1>Reports</h1><p>Generate and manage IERB progress and document summary reports.</p></div><div class="top-controls"><div class="theme-toggle" id="themeToggle"><i class="fa-solid fa-sun light-icon"></i><i class="fa-solid fa-moon dark-icon"></i></div></div></header>
<section class="report-tools"><button class="report-tool" id="openProgressReport"><span class="report-tool-icon"><i class="fa-solid fa-chart-column"></i></span><span><strong>Generate Progress Report</strong><small>All students or a selected IERB stage</small></span><i class="fa-solid fa-chevron-right"></i></button><button class="report-tool" id="openStudentReport"><span class="report-tool-icon"><i class="fa-solid fa-user-graduate"></i></span><span><strong>Generate Student Report</strong><small>Individual IERB progress summary</small></span><i class="fa-solid fa-chevron-right"></i></button><button class="report-tool" id="openDocumentReport"><span class="report-tool-icon"><i class="fa-solid fa-wand-magic-sparkles"></i></span><span><strong>Document Summarizer</strong><small>Create a concise summary PDF</small></span><i class="fa-solid fa-chevron-right"></i></button></section>
<section class="report-history"><div class="report-history-heading"><div><h2>Report History</h2><p id="reportCount">0 reports</p></div><button id="exportExcel"><i class="fa-solid fa-file-excel"></i> Export Excel CSV</button></div><div class="report-table-wrap"><table class="report-table"><thead><tr><th>Report Name</th><th>Date Generated</th><th>Type</th><th>Actions</th></tr></thead><tbody id="reportTableBody"></tbody></table></div></section></main></div>
<div class="report-modal" id="progressModal"><div class="report-modal-dialog"><div class="report-modal-heading"><div><span>PDF generator</span><h2>Progress Report</h2></div><button data-close="progressModal"><i class="fa-solid fa-xmark"></i></button></div><form id="progressForm"><label>Report coverage</label><select id="progressScope"><option value="all">All Students</option><option value="stage">Generate by Stage</option></select><div id="stageChoice" hidden><label>IERB stage</label><select id="reportStage"><option>Stage 1</option><option>Stage 2</option><option>Stage 3</option><option>Stage 4</option><option>Stage 5</option><option>Completed</option></select></div><button class="generate-report-button"><i class="fa-solid fa-file-pdf"></i> Generate PDF</button></form></div></div>
<div class="report-modal" id="studentModal"><div class="report-modal-dialog"><div class="report-modal-heading"><div><span>Individual report</span><h2>Student Progress Report</h2></div><button data-close="studentModal"><i class="fa-solid fa-xmark"></i></button></div><form id="studentReportForm"><label>Select student</label><select id="reportStudent" required></select><button class="generate-report-button"><i class="fa-solid fa-file-pdf"></i> Generate PDF</button></form></div></div>
<div class="report-modal" id="documentModal"><div class="report-modal-dialog"><div class="report-modal-heading"><div><span>Document analysis</span><h2>Document Summary PDF</h2></div><button data-close="documentModal"><i class="fa-solid fa-xmark"></i></button></div><form id="documentReportForm"><label>Select uploaded document</label><select id="reportDocument"></select><span class="report-or">or upload a new document</span><input id="reportDocumentFile" type="file" accept=".pdf,.doc,.docx,.txt,.rtf,.odt"><button class="generate-report-button"><i class="fa-solid fa-wand-magic-sparkles"></i> Summarize to PDF</button></form></div></div>
<script src="assets/js/reports.js"></script><script src="assets/js/dashboard-sidebar.js"></script></body></html>
